# Gitea IngressRoute (HTTP)
# gitea.talos.local → gitea-http:3000
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gitea
  namespace: gitea
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`gitea.talos.local`)
      kind: Rule
      services:
        - name: gitea-http
          port: 3000
  tls: {}
